// import '@/styles/globals.css';

// import type { Metadata } from 'next';
// // eslint-disable-next-line
// import { Inter, Plus_Jakarta_Sans } from 'next/font/google';
// import { Providers } from '@/providers';

// const inter = Inter({ subsets: ['latin'] });
// inter;

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// const fontJakarta = Plus_Jakarta_Sans({
//   subsets: ['latin'],
//   variable: '--font-jakarta',
// });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang='en'>
//       <body className={fontJakarta.className}>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }

import '@/styles/globals.css';

import type { Metadata } from 'next';
// eslint-disable-next-line
import { Inter, Plus_Jakarta_Sans } from 'next/font/google';
import { Providers } from '@/providers';
import { WalletAddressProvider } from '../context/set-wallet-address.context';

const inter = Inter({ subsets: ['latin'] });
inter;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-jakarta',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={fontJakarta.className}>
        <WalletAddressProvider>
          <Providers>{children}</Providers>
        </WalletAddressProvider>
      </body>
    </html>
  );
}
